name: graphml-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - ase>=3.20.1
  - attrs>=20.2.0
  - backcall>=0.2.0
  - backports>=1.0
  - backports.functools_lru_cache>=1.6.1
  - blas>=1.0
  - brotlipy>=0.7.0
  - ca-certificates>=2020.10.14
  - certifi>=2020.6.20
  - cffi>=1.14.3
  - chardet>=3.0.4
  - click>=7.1.2
  - coverage>=5.3
  - cryptography>=3.1.1
  - cycler>=0.10.0
  - decorator>=4.4.2
  - flask>=1.1.2
  - freetype>=2.10.3
  - googledrivedownloader>=0.4
  - h5py>=2.10.0
  - hdf5>=1.10.5
  - html5lib>=1.1
  - idna>=2.10
  - iniconfig>=1.1.0
  - intel-openmp>=2019.4
  - ipykernel>=5.3.4
  - ipython>=7.18.1
  - ipython_genutils>=0.2.0
  - isodate>=0.6.0
  - itsdangerous>=1.1.0
  - jedi>=0.17.2
  - jinja2>=2.11.2
  - joblib>=0.17.0
  - jpeg>=9d
  - keepalive>=0.5
  - kiwisolver>=1.2.0
  - lcms2>=2.11
  - libcxx>=10.0.0
  - libedit>=3.1.20191231
  - libffi>=3.3
  - libllvm9>=9.0.1
  - libmklml>=2019.0.5
  - libpng>=1.6.37
  - libsodium>=1.0.18
  - libtiff>=4.1.0
  - libwebp-base>=1.1.0
  - llvm-openmp>=10.0.0
  - llvmlite>=0.33.0
  - lz4-c>=1.9.2
  - markupsafe>=1.1.1
  - mkl>=2019.4
  - mkl-service>=2.3.0
  - mkl_fft>=1.2.0
  - mkl_random>=1.1.1
  - more-itertools>=8.5.0
  - ncurses>=6.2
  - ninja>=1.10.1
  - numba>=0.50.1
  - olefile>=0.46
  - openssl>=1.1.1h
  - opentsne>=0.3.11
  - packaging>=20.4
  - pandas>=1.0.5
  - parso>=0.7.0
  - pexpect>=4.8.0
  - pickleshare>=0.7.5
  - pillow>=8.0.0
  - pip>=20.2.3
  - pluggy>=0.13.1
  - plyfile>=0.7.2
  - prompt-toolkit>=3.0.8
  - ptyprocess>=0.6.0
  - py>=1.9.0
  - pycparser>=2.20
  - pygments>=2.7.1
  - pynndescent>=0.4.8
  - pyopenssl>=19.1.0
  - pyparsing>=2.4.7
  - pysocks>=1.7.1
  - pytest>=6.1.1
  - pytest-cov>=2.10.1
  - python=3.8.5
  - python-dateutil>=2.8.1
  - pytz>=2020.1
  - pyzmq>=19.0.2
  - rdflib>=5.0.0
  - readline>=8.0
  - requests>=2.24.0
  - setuptools>=50.3.0
  - six>=1.15.0
  - sparqlwrapper>=1.8.5
  - sqlite>=3.33.0
  - threadpoolctl>=2.1.0
  - tk>=8.6.10
  - toml>=0.10.1
  - tornado>=6.0.4
  - tqdm>=4.50.2
  - traitlets>=5.0.5
  - urllib3>=1.25.10
  - wcwidth>=0.2.5
  - webencodings>=0.5.1
  - werkzeug>=1.0.1
  - wheel>=0.35.1
  - xz>=5.2.5
  - zeromq>=4.3.3
  - zlib>=1.2.11
  - zstd>=1.4.5
  - pip:
      - future==0.18.2
